### Обозреваем данные, которые у нас есть

In [ ]:
from sqlalchemy import create_engine

engine = create_engine("postgresql://robot-startml-ro:pheiph0hahj1Vaif@postgres.lab.karpov.courses:6432/startml")
connection = engine.connect().execution_options(stream_results=True)

In [ ]:
import pandas as pd

# Данные по users

users = pd.read_sql(
    """SELECT * FROM public.user_data""",
    con=connection
)

users.head()

   user_id  gender  age country               city  exp_group       os source
0      200       1   34  Russia          Degtyarsk          3  Android    ads
1      201       0   37  Russia             Abakan          0  Android    ads
2      202       1   17  Russia           Smolensk          4  Android    ads
3      203       0   18  Russia             Moscow          1      iOS    ads
4      204       0   36  Russia  Anzhero-Sudzhensk          3  Android    ads

In [ ]:
# Данные по posts

posts = pd.read_sql(
    """SELECT * FROM public.post_text_df""",
    con=connection
)

posts.head()

   post_id                                               text     topic
0        1  UK economy facing major risks\n\nThe UK manufa...  business
1        2  Aids and climate top Davos agenda\n\nClimate c...  business
2        3  Asian quake hits European shares\n\nShares in ...  business
3        4  India power shares jump on debut\n\nShares in ...  business
4        5  Lacroix label bought by US firm\n\nLuxury good...  business

In [ ]:
# Данные по таблице взаимодействия users с  posts

count_feeds = pd.read_sql(
    """SELECT count(*) FROM public.feed_data""",
    con=connection
)

count_feeds.head()

      count
0  76892800

In [ ]:
# Берем 7 миллионов

feeds = pd.read_sql(
    """SELECT * FROM public.feed_data LIMIT 7000000""",
    con=connection
)

feeds.head()

            timestamp  user_id  post_id action  target
0 2021-11-30 13:02:43    70913     2110   view       0
1 2021-11-30 13:05:01    70913     1340   view       0
2 2021-11-30 13:05:17    70913     1140   view       0
3 2021-12-01 19:29:36    70913     4541   view       0
4 2021-12-01 19:32:27    70913      560   view       1

### Работаем с данными и строим фичи для модели

In [5]:
# Посмотрим, сколько записей с action = like, они нам не нужны,
# вся необходимая инофрмация есть в записях с action = view (в поле target)

feeds[feeds.action!='view']

                  timestamp  user_id  post_id action  target
5       2021-12-01 19:33:46    70913      560   like       0
7       2021-12-01 19:33:57    70913      924   like       0
11      2021-12-01 19:39:27    70913      252   like       0
14      2021-12-01 19:42:26    70913     2883   like       0
17      2021-12-01 19:46:56    70913     3089   like       0
...                     ...      ...      ...    ...     ...
6999843 2021-11-20 19:15:43    13718     1254   like       0
6999849 2021-11-20 19:26:05    13718     6751   like       0
6999911 2021-11-25 16:15:53    13718      384   like       0
6999916 2021-11-25 16:21:05    13718     6790   like       0
6999946 2021-12-02 17:14:11    13718     3144   like       0

[751371 rows x 5 columns]

In [6]:
# Удаляем данные с action != view

feeds = feeds[feeds.action=='view']

feeds.head()

            timestamp  user_id  post_id action  target
0 2021-11-30 13:02:43    70913     2110   view       0
1 2021-11-30 13:05:01    70913     1340   view       0
2 2021-11-30 13:05:17    70913     1140   view       0
3 2021-12-01 19:29:36    70913     4541   view       0
4 2021-12-01 19:32:27    70913      560   view       1

Попробуем контентную модель, которая будет предсказывать вероятность лайка для пары (user_id, post_id) на основе информации о пользователе и посте.
Для этого нам нужно построить фичи для пользователей и постов.

In [7]:
# По  users возьмем исходные данные
users

,user_id,gender,age,country,city,exp_group,os,source
0,200,1,34,Russia,Degtyarsk,3,Android,ads
1,201,0,37,Russia,Abakan,0,Android,ads
2,202,1,17,Russia,Smolensk,4,Android,ads
3,203,0,18,Russia,Moscow,1,iOS,ads
4,204,0,36,Russia,Anzhero-Sudzhensk,3,Android,ads
...,...,...,...,...,...,...,...,...
163200,168548,0,36,Russia,Kaliningrad,4,Android,organic
163201,168549,0,18,Russia,Tula,2,Android,organic
163202,168550,1,41,Russia,Yekaterinburg,4,Android,organic
163203,168551,0,38,Russia,Moscow,3,iOS,organic
163204,168552,1,16,Russia,Ivanteyevka,4,Android,organic

In [8]:
# По posts сделаем эмбеддинг для текстов

posts

      post_id                                               text     topic
0           1  UK economy facing major risks\n\nThe UK manufa...  business
1           2  Aids and climate top Davos agenda\n\nClimate c...  business
2           3  Asian quake hits European shares\n\nShares in ...  business
3           4  India power shares jump on debut\n\nShares in ...  business
4           5  Lacroix label bought by US firm\n\nLuxury good...  business
...       ...                                                ...       ...
7018     7315  OK, I would not normally watch a Farrelly brot...     movie
7019     7316  I give this movie 2 stars purely because of it...     movie
7020     7317  I cant believe this film was allowed to be mad...     movie
7021     7318  The version I saw of this film was the Blockbu...     movie
7022     7319  Piece of subtle art. Maybe a masterpiece. Doub...     movie

[7023 rows x 3 columns]

In [9]:
# Попробуем tf-idf, предварительно почистив текст от точек, запятых, 
# переносов строк, предлогов и тд.

import re
import string

from nltk.stem import WordNetLemmatizer 
from sklearn.feature_extraction.text import TfidfVectorizer

wnl = WordNetLemmatizer()

def preprocessing(line, token=wnl):
    line = line.lower()
    line = re.sub(r"[{}]".format(string.punctuation), " ", line)
    line = line.replace('\n\n', ' ').replace('\n', ' ')
    line = ' '.join([token.lemmatize(x) for x in line.split(' ')])
    return line


tfidf = TfidfVectorizer(
    stop_words='english',
    preprocessor=preprocessing
)

In [10]:
tfidf_data = (
    tfidf
    .fit_transform(posts['text'])
    .toarray()
)

tfidf_data

c:\Prog\ForGitHub\StartML\finalproject2\.venv\Lib\site-packages\sklearn\feature_extraction\text.py:411: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['ha', 'wa'] not in stop_words.
  warnings.warn(

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.13273932, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.05061394, 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]], shape=(7023, 46034))

In [11]:
tfidf_data = pd.DataFrame(
    tfidf_data,
    index=posts.post_id,
    columns=tfidf.get_feature_names_out()
)

tfidf_data

,00,000,0001,000bn,000m,000s,000th,001,001and,001st,...,𝓫𝓮,𝓫𝓮𝓽𝓽𝓮𝓻,𝓬𝓸𝓾𝓻𝓽𝓼,𝓱𝓮𝓪𝓻𝓲𝓷𝓰,𝓶𝓪𝔂,𝓹𝓱𝔂𝓼𝓲𝓬𝓪𝓵,𝓼𝓸𝓸𝓷𝓮𝓻,𝓼𝓾𝓫𝓸𝓻𝓭𝓲𝓷𝓪𝓽𝓮,𝓽𝓱𝓮,𝓽𝓸
post_id,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.132739,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.050614,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7315,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7316,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7317,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7318,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7319,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
[f"DistanceTo{ith}thCluster" for ith in range(1, 11)]

['DistanceTo1thCluster',
 'DistanceTo2thCluster',
 'DistanceTo3thCluster',
 'DistanceTo4thCluster',
 'DistanceTo5thCluster',
 'DistanceTo6thCluster',
 'DistanceTo7thCluster',
 'DistanceTo8thCluster',
 'DistanceTo9thCluster',
 'DistanceTo10thCluster']

In [13]:
# Кластеризуем тексты

from sklearn.decomposition import PCA

centered = tfidf_data - tfidf_data.mean()

pca = PCA(n_components=20)
pca_decomp = pca.fit_transform(centered)

from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=10, random_state=0).fit(pca_decomp)

posts['TextCluster'] = kmeans.labels_

dists_columns = ['DistanceTo1thCluster',
                 'DistanceTo2thCluster',
                 'DistanceTo3thCluster',
                 'DistanceTo4thCluster',
                 'DistanceTo5thCluster',
                 'DistanceTo6thCluster',
                 'DistanceTo7thCluster',
                 'DistanceTo8thCluster',
                 'DistanceTo9thCluster',
                 'DistanceTo10thCluster']

dists_df = pd.DataFrame(
    data=kmeans.transform(pca_decomp),
    columns=dists_columns
)

dists_df.head()

,DistanceTo1thCluster,DistanceTo2thCluster,DistanceTo3thCluster,DistanceTo4thCluster,DistanceTo5thCluster,DistanceTo6thCluster,DistanceTo7thCluster,DistanceTo8thCluster,DistanceTo9thCluster,DistanceTo10thCluster
0,0.496114,0.441481,0.448593,0.499339,0.439971,0.473618,0.392266,0.460609,0.524966,0.153522
1,0.363963,0.301639,0.308137,0.373440,0.289866,0.337942,0.172502,0.324854,0.263704,0.247537
2,0.390693,0.333217,0.334385,0.388518,0.314463,0.361705,0.243309,0.360441,0.472770,0.119871
3,0.318380,0.296560,0.276428,0.351341,0.263534,0.319323,0.158768,0.318176,0.423497,0.216953
4,0.290771,0.227819,0.197219,0.294312,0.178171,0.258187,0.089412,0.293180,0.385198,0.279012

In [14]:
posts = pd.concat((posts,dists_df), axis=1)

posts.head()

,post_id,text,topic,TextCluster,DistanceTo1thCluster,DistanceTo2thCluster,DistanceTo3thCluster,DistanceTo4thCluster,DistanceTo5thCluster,DistanceTo6thCluster,DistanceTo7thCluster,DistanceTo8thCluster,DistanceTo9thCluster,DistanceTo10thCluster
0,1,UK economy facing major risks\n\nThe UK manufa...,business,9,0.496114,0.441481,0.448593,0.499339,0.439971,0.473618,0.392266,0.460609,0.524966,0.153522
1,2,Aids and climate top Davos agenda\n\nClimate c...,business,6,0.363963,0.301639,0.308137,0.373440,0.289866,0.337942,0.172502,0.324854,0.263704,0.247537
2,3,Asian quake hits European shares\n\nShares in ...,business,9,0.390693,0.333217,0.334385,0.388518,0.314463,0.361705,0.243309,0.360441,0.472770,0.119871
3,4,India power shares jump on debut\n\nShares in ...,business,6,0.318380,0.296560,0.276428,0.351341,0.263534,0.319323,0.158768,0.318176,0.423497,0.216953
4,5,Lacroix label bought by US firm\n\nLuxury good...,business,6,0.290771,0.227819,0.197219,0.294312,0.178171,0.258187,0.089412,0.293180,0.385198,0.279012

In [15]:
# Построим датафрейм с новыми фичами 

df = pd.merge(feeds,
              posts,
              on='post_id',
              how='left')

df.head()

,timestamp,user_id,post_id,action,target,text,topic,TextCluster,DistanceTo1thCluster,DistanceTo2thCluster,DistanceTo3thCluster,DistanceTo4thCluster,DistanceTo5thCluster,DistanceTo6thCluster,DistanceTo7thCluster,DistanceTo8thCluster,DistanceTo9thCluster,DistanceTo10thCluster
0,2021-11-30 13:02:43,70913,2110,view,0,The pirates with no profit motive\n\nTwo men w...,tech,6,0.416433,0.321710,0.346609,0.375256,0.303654,0.350394,0.201515,0.319504,0.383066,0.375952
1,2021-11-30 13:05:01,70913,1340,view,0,Retirement age could be scrapped\n\nThe myth t...,politics,6,0.365972,0.279756,0.278860,0.338569,0.245524,0.305865,0.166742,0.335518,0.254366,0.305774
2,2021-11-30 13:05:17,70913,1140,view,0,Howard rebuts asylum criticisms\n\nTory leader...,politics,8,0.516712,0.439365,0.457372,0.467104,0.412275,0.426131,0.379402,0.470420,0.139711,0.505068
3,2021-12-01 19:29:36,70913,4541,view,0,Im sorry but this is just awful. I have told p...,movie,4,0.342415,0.264802,0.271290,0.199819,0.168642,0.208986,0.246197,0.357136,0.424464,0.373385
4,2021-12-01 19:32:27,70913,560,view,1,Director Nairs Vanity project\n\nIndian film d...,entertainment,5,0.372953,0.275481,0.320314,0.308463,0.211489,0.162205,0.244353,0.368464,0.434839,0.362463

In [16]:
df = pd.merge(df,
              users,
              on='user_id',
              how='left')

df.head()

,timestamp,user_id,post_id,action,target,text,topic,TextCluster,DistanceTo1thCluster,DistanceTo2thCluster,...,DistanceTo8thCluster,DistanceTo9thCluster,DistanceTo10thCluster,gender,age,country,city,exp_group,os,source
0,2021-11-30 13:02:43,70913,2110,view,0,The pirates with no profit motive\n\nTwo men w...,tech,6,0.416433,0.321710,...,0.319504,0.383066,0.375952,0,29,Russia,Dolgoprudnyy,2,Android,ads
1,2021-11-30 13:05:01,70913,1340,view,0,Retirement age could be scrapped\n\nThe myth t...,politics,6,0.365972,0.279756,...,0.335518,0.254366,0.305774,0,29,Russia,Dolgoprudnyy,2,Android,ads
2,2021-11-30 13:05:17,70913,1140,view,0,Howard rebuts asylum criticisms\n\nTory leader...,politics,8,0.516712,0.439365,...,0.470420,0.139711,0.505068,0,29,Russia,Dolgoprudnyy,2,Android,ads
3,2021-12-01 19:29:36,70913,4541,view,0,Im sorry but this is just awful. I have told p...,movie,4,0.342415,0.264802,...,0.357136,0.424464,0.373385,0,29,Russia,Dolgoprudnyy,2,Android,ads
4,2021-12-01 19:32:27,70913,560,view,1,Director Nairs Vanity project\n\nIndian film d...,entertainment,5,0.372953,0.275481,...,0.368464,0.434839,0.362463,0,29,Russia,Dolgoprudnyy,2,Android,ads

In [17]:
# Выделим час и месяц из дат

df['hour'] = pd.to_datetime(df['timestamp']).apply(lambda x: x.hour)
df['month'] = pd.to_datetime(df['timestamp']).apply(lambda x: x.month)

df.head()

,timestamp,user_id,post_id,action,target,text,topic,TextCluster,DistanceTo1thCluster,DistanceTo2thCluster,...,DistanceTo10thCluster,gender,age,country,city,exp_group,os,source,hour,month
0,2021-11-30 13:02:43,70913,2110,view,0,The pirates with no profit motive\n\nTwo men w...,tech,6,0.416433,0.321710,...,0.375952,0,29,Russia,Dolgoprudnyy,2,Android,ads,13,11
1,2021-11-30 13:05:01,70913,1340,view,0,Retirement age could be scrapped\n\nThe myth t...,politics,6,0.365972,0.279756,...,0.305774,0,29,Russia,Dolgoprudnyy,2,Android,ads,13,11
2,2021-11-30 13:05:17,70913,1140,view,0,Howard rebuts asylum criticisms\n\nTory leader...,politics,8,0.516712,0.439365,...,0.505068,0,29,Russia,Dolgoprudnyy,2,Android,ads,13,11
3,2021-12-01 19:29:36,70913,4541,view,0,Im sorry but this is just awful. I have told p...,movie,4,0.342415,0.264802,...,0.373385,0,29,Russia,Dolgoprudnyy,2,Android,ads,19,12
4,2021-12-01 19:32:27,70913,560,view,1,Director Nairs Vanity project\n\nIndian film d...,entertainment,5,0.372953,0.275481,...,0.362463,0,29,Russia,Dolgoprudnyy,2,Android,ads,19,12

In [18]:
# Уберем ненужные колонки

df = df.drop([
    'action',
    'text',
],
    axis=1)

df = df.set_index(['user_id', 'post_id'])

df.head(20)

                          timestamp  target          topic  TextCluster  \
user_id post_id
70913   2110    2021-11-30 13:02:43       0           tech            6
        1340    2021-11-30 13:05:01       0       politics            6
        1140    2021-11-30 13:05:17       0       politics            8
        4541    2021-12-01 19:29:36       0          movie            4
        560     2021-12-01 19:32:27       1  entertainment            5
        924     2021-12-01 19:33:48       1  entertainment            5
        4621    2021-12-01 19:33:59       0          movie            3
        3929    2021-12-01 19:36:26       0          covid            0
        252     2021-12-01 19:37:51       1       business            6
        7202    2021-12-01 19:39:29       0          movie            4
        2883    2021-12-01 19:40:56       1          covid            2
        6498    2021-12-01 19:42:28       0          movie            3
        3089    2021-12-01 19:44:45       1          covid            2
        5227    2021-12-01 19:46:58       0          movie            3
        2967    2021-12-01 19:49:41       0          covid            2
        6834    2021-12-01 19:51:06       0          movie            5
        7076    2021-12-01 19:52:39       1          movie            4
        5983    2021-12-01 19:52:54       0          movie            5
        6030    2021-12-01 19:54:39       0          movie            5
        1719    2021-12-01 19:56:56       0          sport            1

                 DistanceTo1thCluster  DistanceTo2thCluster  \
user_id post_id
70913   2110                 0.416433              0.321710
        1340                 0.365972              0.279756
        1140                 0.516712              0.439365
        4541                 0.342415              0.264802
        560                  0.372953              0.275481
        924                  0.556364              0.492687
        4621                 0.460137              0.414478
        3929                 0.068032              0.332416
        252                  0.556614              0.524251
        7202                 0.308923              0.221840
        2883                 0.245099              0.333627
        6498                 0.374419              0.308262
        3089                 0.258834              0.296759
        5227                 0.349348              0.268370
        2967                 0.244162              0.241858
        6834                 0.363104              0.297202
        7076                 0.312617              0.227704
        5983                 0.354676              0.347529
        6030                 0.346376              0.279192
        1719                 0.396425              0.109637

                 DistanceTo3thCluster  DistanceTo4thCluster  \
user_id post_id
70913   2110                 0.346609              0.375256
        1340                 0.278860              0.338569
        1140                 0.457372              0.467104
        4541                 0.271290              0.199819
        560                  0.320314              0.308463
        924                  0.507880              0.512651
        4621                 0.397871              0.173670
        3929                 0.196130              0.375109
        252                  0.516403              0.550869
        7202                 0.207340              0.241774
        2883                 0.110286              0.363723
        6498                 0.295698              0.162721
        3089                 0.090055              0.335073
        5227                 0.257728              0.126560
        2967                 0.073343              0.287470
        6834                 0.277589              0.258519
        7076                 0.220605              0.217102
        5983                 0.310173              0.264308
        6030                 0.299456              0.292915
        1719                 0.321932              0.366497

                 DistanceTo5thCluster  DistanceTo6thCluster  ...  \
user_id post_id                                              ...
70913   2110                 0.303654              0.350394  ...
        1340                 0.245524              0.305865  ...
        1140                 0.412275              0.426131  ...
        4541                 0.168642              0.208986  ...
        560                  0.211489              0.162205  ...
        924                  0.448305              0.311156  ...
        4621                 0.312887              0.325322  ...
        3929                 0.286817              0.346401  ...
        252                  0.499848              0.533131  ...
        7202                 0.086509              0.202829  ...
        2883                 0.280775              0.338412  ...
        6498                 0.173222              0.193766  ...
        3089                 0.230827              0.307281  ...
        5227                 0.141845              0.197990  ...
        2967                 0.165931              0.260093  ...
        6834                 0.178233              0.070406  ...
        7076                 0.070847              0.129529  ...
        5983                 0.245204              0.168560  ...
        6030                 0.181719              0.163200  ...
        1719                 0.280497              0.339700  ...

                 DistanceTo10thCluster  gender  age  country          city  \
user_id post_id
70913   2110                  0.375952       0   29   Russia  Dolgoprudnyy
        1340                  0.305774       0   29   Russia  Dolgoprudnyy
        1140                  0.505068       0   29   Russia  Dolgoprudnyy
        4541                  0.373385       0   29   Russia  Dolgoprudnyy
        560                   0.362463       0   29   Russia  Dolgoprudnyy
        924                   0.534184       0   29   Russia  Dolgoprudnyy
        4621                  0.481647       0   29   Russia  Dolgoprudnyy
        3929                  0.385871       0   29   Russia  Dolgoprudnyy
        252                   0.448718       0   29   Russia  Dolgoprudnyy
        7202                  0.319460       0   29   Russia  Dolgoprudnyy
        2883                  0.392816       0   29   Russia  Dolgoprudnyy
        6498                  0.396994       0   29   Russia  Dolgoprudnyy
        3089                  0.304259       0   29   Russia  Dolgoprudnyy
        5227                  0.351543       0   29   Russia  Dolgoprudnyy
        2967                  0.330074       0   29   Russia  Dolgoprudnyy
        6834                  0.372481       0   29   Russia  Dolgoprudnyy
        7076                  0.343370       0   29   Russia  Dolgoprudnyy
        5983                  0.394650       0   29   Russia  Dolgoprudnyy
        6030                  0.357302       0   29   Russia  Dolgoprudnyy
        1719                  0.384888       0   29   Russia  Dolgoprudnyy

                 exp_group       os source  hour month
user_id post_id
70913   2110             2  Android    ads    13    11
        1340             2  Android    ads    13    11
        1140             2  Android    ads    13    11
        4541             2  Android    ads    19    12
        560              2  Android    ads    19    12
        924              2  Android    ads    19    12
        4621             2  Android    ads    19    12
        3929             2  Android    ads    19    12
        252              2  Android    ads    19    12
        7202             2  Android    ads    19    12
        2883             2  Android    ads    19    12
        6498             2  Android    ads    19    12
        3089             2  Android    ads    19    12
        5227             2  Android    ads    19    12
        2967             2  Android    ads    19    12
        6834             2  Android    ads    19    12
        7076             2  Android    ads    19    12
        5983             2  Android    ads    19    12
        6030             2  Android    ads    19    12
        1719             2  Android    ads    19    12

[20 rows x 23 columns]

### Обучение модели

In [19]:
# Разобьем на train и test по временному признаку

max(df.timestamp), min(df.timestamp)

(Timestamp('2021-12-29 23:51:06'), Timestamp('2021-10-01 06:05:25'))

In [20]:
# Возьмем за границу 2021-12-15

df_train = df[df.timestamp < '2021-12-15']
df_test = df[df.timestamp >= '2021-12-15']

df_train = df_train.drop('timestamp', axis=1)
df_test = df_test.drop('timestamp', axis=1)

x_train = df_train.drop('target', axis=1)
x_test = df_test.drop('target', axis=1)

y_train = df_train['target']
y_test = df_test['target']

y_train.shape, y_test.shape

((5195602,), (1053027,))

In [21]:
x_train

                         topic  TextCluster  DistanceTo1thCluster  \
user_id post_id
70913   2110              tech            6              0.416433
        1340          politics            6              0.365972
        1140          politics            8              0.516712
        4541             movie            4              0.342415
        560      entertainment            5              0.372953
...                        ...          ...                   ...
13718   6575             movie            4              0.330284
        386           business            6              0.328507
        3664             covid            2              0.311959
        5782             movie            5              0.457402
        3271             covid            2              0.233836

                 DistanceTo2thCluster  DistanceTo3thCluster  \
user_id post_id
70913   2110                 0.321710              0.346609
        1340                 0.279756              0.278860
        1140                 0.439365              0.457372
        4541                 0.264802              0.271290
        560                  0.275481              0.320314
...                               ...                   ...
13718   6575                 0.222089              0.237922
        386                  0.267139              0.249024
        3664                 0.401332              0.265349
        5782                 0.401670              0.398894
        3271                 0.323616              0.099037

                 DistanceTo4thCluster  DistanceTo5thCluster  \
user_id post_id
70913   2110                 0.375256              0.303654
        1340                 0.338569              0.245524
        1140                 0.467104              0.412275
        4541                 0.199819              0.168642
        560                  0.308463              0.211489
...                               ...                   ...
13718   6575                 0.232577              0.123184
        386                  0.293882              0.171368
        3664                 0.435413              0.367495
        5782                 0.290441              0.282273
        3271                 0.361621              0.273375

                 DistanceTo6thCluster  DistanceTo7thCluster  \
user_id post_id
70913   2110                 0.350394              0.201515
        1340                 0.305865              0.166742
        1140                 0.426131              0.379402
        4541                 0.208986              0.246197
        560                  0.162205              0.244353
...                               ...                   ...
13718   6575                 0.224129              0.208023
        386                  0.255604              0.170731
        3664                 0.412863              0.375438
        5782                 0.170017              0.391410
        3271                 0.334489              0.285708

                 DistanceTo8thCluster  ...  DistanceTo10thCluster  gender  \
user_id post_id                        ...
70913   2110                 0.319504  ...               0.375952       0
        1340                 0.335518  ...               0.305774       0
        1140                 0.470420  ...               0.505068       0
        4541                 0.357136  ...               0.373385       0
        560                  0.368464  ...               0.362463       0
...                               ...  ...                    ...     ...
13718   6575                 0.352535  ...               0.333742       1
        386                  0.254140  ...               0.321488       1
        3664                 0.468222  ...               0.459981       1
        5782                 0.464143  ...               0.474661       1
        3271                 0.389126  ...               0.395542       1

                 age  country          city exp_group       os source hour  \
user_id post_id
70913   2110      29   Russia  Dolgoprudnyy         2  Android    ads   13
        1340      29   Russia  Dolgoprudnyy         2  Android    ads   13
        1140      29   Russia  Dolgoprudnyy         2  Android    ads   13
        4541      29   Russia  Dolgoprudnyy         2  Android    ads   19
        560       29   Russia  Dolgoprudnyy         2  Android    ads   19
...              ...      ...           ...       ...      ...    ...  ...
13718   6575      43   Russia         Kazan         3      iOS    ads    7
        386       43   Russia         Kazan         3      iOS    ads    7
        3664      43   Russia         Kazan         3      iOS    ads    7
        5782      43   Russia         Kazan         3      iOS    ads    7
        3271      43   Russia         Kazan         3      iOS    ads    7

                 month
user_id post_id
70913   2110        11
        1340        11
        1140        11
        4541        12
        560         12
...                ...
13718   6575        12
        386         12
        3664        12
        5782        12
        3271        12

[5195602 rows x 21 columns]

In [23]:
# Обучим катбуст

from catboost import CatBoostClassifier

object_cols = [
    'topic', 'TextCluster', 'gender', 'country',
    'city', 'exp_group', 'hour', 'month',
    'os', 'source'
]

catboost = CatBoostClassifier(iterations=100,
                              learning_rate=1,
                              depth=2)

catboost.fit(x_train, y_train, object_cols)

0:	learn: 0.3579863	total: 789ms	remaining: 1m 18s
1:	learn: 0.3510437	total: 1.31s	remaining: 1m 4s
2:	learn: 0.3498695	total: 1.84s	remaining: 59.5s
3:	learn: 0.3490983	total: 2.36s	remaining: 56.8s
4:	learn: 0.3489731	total: 2.88s	remaining: 54.8s
5:	learn: 0.3488526	total: 3.54s	remaining: 55.4s
6:	learn: 0.3487792	total: 4s	remaining: 53.1s
7:	learn: 0.3487309	total: 4.44s	remaining: 51.1s
8:	learn: 0.3483473	total: 4.9s	remaining: 49.6s
9:	learn: 0.3475074	total: 5.36s	remaining: 48.2s
10:	learn: 0.3474807	total: 5.78s	remaining: 46.8s
11:	learn: 0.3473770	total: 6.26s	remaining: 45.9s
12:	learn: 0.3468836	total: 6.71s	remaining: 44.9s
13:	learn: 0.3466950	total: 7.15s	remaining: 43.9s
14:	learn: 0.3465897	total: 7.58s	remaining: 43s
15:	learn: 0.3463874	total: 8.06s	remaining: 42.3s
16:	learn: 0.3463604	total: 8.47s	remaining: 41.4s
17:	learn: 0.3462929	total: 8.9s	remaining: 40.5s
18:	learn: 0.3462754	total: 9.32s	remaining: 39.7s
19:	learn: 0.3462111	total: 9.78s	remaining: 39.1s
20:	learn: 0.3458359	total: 10.2s	remaining: 38.5s
21:	learn: 0.3458047	total: 10.7s	remaining: 37.8s
22:	learn: 0.3457886	total: 11.1s	remaining: 37.1s
23:	learn: 0.3457053	total: 11.5s	remaining: 36.6s
24:	learn: 0.3456329	total: 12s	remaining: 36s
25:	learn: 0.3451831	total: 12.5s	remaining: 35.5s
26:	learn: 0.3450820	total: 12.9s	remaining: 34.9s
27:	learn: 0.3447637	total: 13.4s	remaining: 34.4s
28:	learn: 0.3447516	total: 13.8s	remaining: 33.7s
29:	learn: 0.3447360	total: 14.2s	remaining: 33.1s
30:	learn: 0.3447213	total: 14.7s	remaining: 32.6s
31:	learn: 0.3447099	total: 15.1s	remaining: 32.1s
32:	learn: 0.3442560	total: 15.6s	remaining: 31.6s
33:	learn: 0.3441801	total: 16s	remaining: 31s
34:	learn: 0.3440728	total: 16.4s	remaining: 30.5s
35:	learn: 0.3440510	total: 16.9s	remaining: 30s
36:	learn: 0.3440299	total: 17.3s	remaining: 29.4s
37:	learn: 0.3440157	total: 17.7s	remaining: 28.9s
38:	learn: 0.3439975	total: 18.1s	remaining: 28.4s
39:	learn: 0.3439881	total: 18.6s	remaining: 27.8s
40:	learn: 0.3439831	total: 19s	remaining: 27.3s
41:	learn: 0.3438729	total: 19.4s	remaining: 26.8s
42:	learn: 0.3438388	total: 19.9s	remaining: 26.3s
43:	learn: 0.3438284	total: 20.3s	remaining: 25.8s
44:	learn: 0.3438234	total: 20.7s	remaining: 25.3s
45:	learn: 0.3437467	total: 21.2s	remaining: 24.9s
46:	learn: 0.3437342	total: 21.6s	remaining: 24.4s
47:	learn: 0.3437120	total: 22s	remaining: 23.9s
48:	learn: 0.3436906	total: 22.5s	remaining: 23.4s
49:	learn: 0.3436048	total: 23s	remaining: 23s
50:	learn: 0.3435563	total: 23.4s	remaining: 22.5s
51:	learn: 0.3435469	total: 23.9s	remaining: 22s
52:	learn: 0.3435354	total: 24.3s	remaining: 21.6s
53:	learn: 0.3435271	total: 24.7s	remaining: 21.1s
54:	learn: 0.3434889	total: 25.2s	remaining: 20.6s
55:	learn: 0.3434772	total: 25.6s	remaining: 20.1s
56:	learn: 0.3434653	total: 26s	remaining: 19.6s
57:	learn: 0.3434588	total: 26.5s	remaining: 19.2s
58:	learn: 0.3434459	total: 26.9s	remaining: 18.7s
59:	learn: 0.3434335	total: 27.3s	remaining: 18.2s
60:	learn: 0.3434008	total: 27.8s	remaining: 17.8s
61:	learn: 0.3433939	total: 28.3s	remaining: 17.3s
62:	learn: 0.3433891	total: 28.7s	remaining: 16.9s
63:	learn: 0.3433802	total: 29.1s	remaining: 16.4s
64:	learn: 0.3433721	total: 29.6s	remaining: 15.9s
65:	learn: 0.3433640	total: 30s	remaining: 15.5s
66:	learn: 0.3433539	total: 30.4s	remaining: 15s
67:	learn: 0.3433463	total: 30.9s	remaining: 14.5s
68:	learn: 0.3433314	total: 31.3s	remaining: 14.1s
69:	learn: 0.3433259	total: 31.7s	remaining: 13.6s
70:	learn: 0.3432987	total: 32.1s	remaining: 13.1s
71:	learn: 0.3432862	total: 32.6s	remaining: 12.7s
72:	learn: 0.3432635	total: 33s	remaining: 12.2s
73:	learn: 0.3432447	total: 33.4s	remaining: 11.8s
74:	learn: 0.3432365	total: 33.9s	remaining: 11.3s
75:	learn: 0.3432308	total: 34.3s	remaining: 10.8s
76:	learn: 0.3432217	total: 34.7s	remaining: 10.4s
77:	learn: 0.3432115	total: 35.2s	remaining: 9.92s
78:	learn: 0.3432043	total: 35.6s	remaining: 9.46s
79:	learn: 0.3431894	total: 36s	remaining: 9.01s
80:	learn: 0.3431804	total: 36.5s	remaining: 8.55s
81:	learn: 0.3431673	total: 36.9s	remaining: 8.1s
82:	learn: 0.3431327	total: 37.3s	remaining: 7.65s
83:	learn: 0.3431223	total: 37.8s	remaining: 7.2s
84:	learn: 0.3431158	total: 38.2s	remaining: 6.75s
85:	learn: 0.3431137	total: 38.7s	remaining: 6.3s
86:	learn: 0.3431111	total: 39.2s	remaining: 5.86s
87:	learn: 0.3431084	total: 39.7s	remaining: 5.41s
88:	learn: 0.3431073	total: 40.2s	remaining: 4.96s
89:	learn: 0.3431024	total: 40.6s	remaining: 4.51s
90:	learn: 0.3430946	total: 41.1s	remaining: 4.06s
91:	learn: 0.3430807	total: 41.5s	remaining: 3.61s
92:	learn: 0.3430743	total: 42s	remaining: 3.16s
93:	learn: 0.3430627	total: 42.4s	remaining: 2.71s
94:	learn: 0.3430535	total: 42.9s	remaining: 2.26s
95:	learn: 0.3430451	total: 43.3s	remaining: 1.8s
96:	learn: 0.3430389	total: 43.7s	remaining: 1.35s
97:	learn: 0.3430302	total: 44.2s	remaining: 902ms
98:	learn: 0.3430240	total: 44.7s	remaining: 451ms
99:	learn: 0.3430157	total: 45.1s	remaining: 0us

CatBoostClassifier(depth=2, iterations=100, learning_rate=1)

In [25]:
# Замерим качество работы такой модели с помощью ROC-AUC

from sklearn.metrics import roc_auc_score

print(f"Качество на трейне: {roc_auc_score(y_train, catboost.predict_proba(x_train)[:, 1])}")
print(f"Качество на тесте: {roc_auc_score(y_test, catboost.predict_proba(x_test)[:, 1])}")

Качество на трейне: 0.6672537679461172
Качество на тесте: 0.6486532336047529

In [ ]:
# Сохраняем модель

catboost.save_model(
    'catboost_model.cbm',
    format="cbm"                  
)

### Сохраняем в базу фичи, необходимые для функционала модели

In [ ]:
posts.to_sql(    
   "vl_aleksandrov_posts_info_features",                    
    con=connection,                      
    schema="public",                   
    if_exists='replace'            
   )

23

In [ ]:
# Проверяем, сохранились ли данные

test_ = pd.read_sql(
    """SELECT * FROM vl_aleksandrov_posts_info_features""",
    con=connection
    )   
test_

,index,post_id,text,topic,TextCluster,DistanceTo1thCluster,DistanceTo2thCluster,DistanceTo3thCluster,DistanceTo4thCluster,DistanceTo5thCluster,DistanceTo6thCluster,DistanceTo7thCluster,DistanceTo8thCluster,DistanceTo9thCluster,DistanceTo10thCluster
0,0,1,UK economy facing major risks\n\nThe UK manufa...,business,9,0.496114,0.441481,0.448593,0.499339,0.439971,0.473618,0.392266,0.460609,0.524966,0.153522
1,1,2,Aids and climate top Davos agenda\n\nClimate c...,business,6,0.363963,0.301639,0.308137,0.373440,0.289866,0.337942,0.172502,0.324854,0.263704,0.247537
2,2,3,Asian quake hits European shares\n\nShares in ...,business,9,0.390693,0.333217,0.334385,0.388518,0.314463,0.361705,0.243309,0.360441,0.472770,0.119871
3,3,4,India power shares jump on debut\n\nShares in ...,business,6,0.318380,0.296560,0.276428,0.351341,0.263534,0.319323,0.158768,0.318176,0.423497,0.216953
4,4,5,Lacroix label bought by US firm\n\nLuxury good...,business,6,0.290771,0.227819,0.197219,0.294312,0.178171,0.258187,0.089412,0.293180,0.385198,0.279012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7018,7018,7315,"OK, I would not normally watch a Farrelly brot...",movie,3,0.423119,0.353898,0.355335,0.124308,0.245218,0.318394,0.339755,0.427543,0.489768,0.435878
7019,7019,7316,I give this movie 2 stars purely because of it...,movie,3,0.379312,0.328702,0.298206,0.078847,0.202838,0.243710,0.286092,0.378001,0.462984,0.389795
7020,7020,7317,I cant believe this film was allowed to be mad...,movie,5,0.339570,0.286478,0.254895,0.273173,0.163305,0.082132,0.252135,0.365161,0.447956,0.375346
7021,7021,7318,The version I saw of this film was the Blockbu...,movie,5,0.378144,0.302925,0.301603,0.277103,0.190815,0.160998,0.266590,0.381498,0.444868,0.381894
7022,7022,7319,Piece of subtle art. Maybe a masterpiece. Doub...,movie,4,0.303801,0.239802,0.192458,0.231049,0.103825,0.184533,0.187544,0.330364,0.415189,0.336716